export const HYDERABAD_LOCALITIES: string[] = [
  "Abids",
  "Adikmet",
  "Afzalgunj",
  "Alwal",
  "Ameerpet",
  "Ashok Nagar",
  "Attapur",
  "Bachupally",
  "Bahadurpura",
  "Balkampet",
  "Banjara Hills",
  "Basheerbagh",
  "Begum Bazar",
  "Begumpet",
  "BHEL",
  "Boduppal",
  "Bolarum",
  "Borabanda",
  "Bowenpally",
  "Charminar",
  "Chandanagar",
  "Chikkadpally",
  "Dilsukhnagar",
  "ECIL",
  "Erragadda",
  "Erramanzil",
  "Falaknuma",
  "Film Nagar",
  "Financial District",
  "Gachibowli",
  "Gandipet",
  "Ghatkesar",
  "Habsiguda",
  "Hayathnagar",
  "Himayatnagar",
  "Hitech City",
  "JNTU",
  "Jeedimetla",
  "Jubilee Hills",
  "Kachiguda",
  "Kompally",
  "Kondapur",
  "Kothapet",
  "Koti",
  "Khairatabad",
  "Kismatpur",
  "KPHB",
  "LB Nagar",
  "Lingampally",
  "Madhapur",
  "Malkajgiri",
  "Mallapur",
  "Manikonda",
  "Marredpally",
  "Masab Tank",
  "Medchal",
  "Mehdipatnam",
  "Miyapur",
  "Moosapet",
  "Moosarambagh",
  "Musheerabad",
  "Nacharam",
  "Nallagandla",
  "Nampally",
  "Nanankramguda",
  "Narsingi",
  "Nizampet",
  "Osmania University",
  "Panjagutta",
  "Patancheru",
  "Peerzadiguda",
  "Pragathi Nagar",
  "Punjagutta",
  "Raidurg",
  "Rajendranagar",
  "Ramanthapur",
  "Sainikpuri",
  "Sanathnagar",
  "Saroornagar",
  "Secunderabad",
  "Serilingampally",
  "Shaikpet",
  "Shalibanda",
  "Shamshabad",
  "Somajiguda",
  "SR Nagar",
  "Suchitra",
  "Tarnaka",
  "Tellapur",
  "Toli Chowki",
  "Trimulgherry",
  "Uppal",
  "Vidyanagar",
  "Yapral",
  "Yousufguda",
];


